config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'active_support/security_utils'
require 'subdomain_routes'
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications

    controllers tokens: 'agents/tokens'

    # controllers applications: 'agents/authorizations',
    # tokens: 'agents/custom_authorizations'
    # authorizations: 'custom_authorizations',
    #    tokens: 'custom_authorizations',
    #    applications: 'custom_authorizations',
    #    token_info: 'custom_authorizations'
  end

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?

  post '/graphql', to: 'graphql#execute'
  post '/api/graphql', to: 'api/graphql#execute'
  get :widget, to: 'widgets#show', path: '/embed'

  get :show, to: 'api/v1/credentials#show', path: '/api/v1/me'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking
    ActiveSupport::SecurityUtils.secure_compare(user, Chaskiq::Config.get('ADMIN_EMAIL')) &
      ActiveSupport::SecurityUtils.secure_compare(password.to_s, Chaskiq::Config.get('ADMIN_PASSWORD').to_s)
  end

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :agents, controllers: {
    registrations: 'agents/registrations',
    invitations: 'agents/invitations',
    sessions: 'agents/sessions',
    omniauth_callbacks: 'agents/omniauth_callbacks',
    passwords: 'agents/passwords'
  } do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_agent_session
  end

  post "/auth0/authenticate", to: "agents/auth0#create"

  resource :oembed, controller: 'oembed', only: :show
  get '/package_iframe/:package' => 'application#package_iframe'
  post '/package_iframe_internal/:package' => 'application#package_iframe_internal'
  post '/dummy_webhook' => 'application#dummy_webhook'

  constraints(SubdomainOrDomain) do
    # TODO, regex ?
    get '/' => 'articles#show'
    get '/:lang' => 'articles#show'
    get '/:lang/collections' => 'articles#show'
    get '/:lang/collections/:id' => 'articles#show'
    get '/:lang/articles/:id' => 'articles#show'
    get '/collections' => 'articles#show'
    get '/collections/:id' => 'articles#show'
    get '/articles/:1/' => 'articles#show'
  end

  root to: 'home#show'
  get '/apps/:app/premailer/:id/' => 'application#preview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'tester' => 'client_tester#show'
  get 'tester/:id' => 'client_tester#show'
  get 'tester/:id/:id2' => 'client_tester#show'
  get 'tester/:id/:id2/id3' => 'client_tester#show'
  get 'tester/:id/:id2/id3/:id4' => 'client_tester#show'

  get '/' => 'home#show', as: :agents

  scope path: '/api' do
    scope path: '/v1' do
      resources :hooks, only: [:create], controller: 'api/v1/hooks'

      post 'hooks/global/:provider' => 'api/v1/hooks/provider#global_process_event'
      get 'hooks/global/:provider' => 'api/v1/hooks/provider#global_process_event'

      post 'hooks/receiver/:id' => 'api/v1/hooks/provider#process_event'
      get 'hooks/receiver/:id' => 'api/v1/hooks/provider#process_event'


      post 'oauth/global/callback' => 'api/v1/hooks/provider#oauth'
      get 'oauth/global/callback' => 'api/v1/hooks/provider#oauth'
      
      post 'oauth/callback/:id' => 'api/v1/hooks/provider#oauth'
      get 'oauth/callback/:id' => 'api/v1/hooks/provider#oauth'

      # get 'oauth/:app_key/:provider/:id' => 'api/v1/hooks/provider#oauth'
      # get 'hooks/:app_key/:provider/:id' => 'api/v1/hooks/provider#create'
      # post 'hooks/:app_key/:provider/:id' => 'api/v1/hooks/provider#process_event'

      resources :direct_uploads, only: [:create], controller: 'api/v1/direct_uploads'

      resources :stripe_hooks, only: [:create], controller: 'api/v1/subscriptions/stripe_hooks'
      resources :subscription_hooks, only: [:create], controller: 'api/v1/subscriptions/paddle_hooks'
    end
  end

  get '*path', to: 'application#catch_all', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaskiq App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/png" href="<%= asset_url('favicon.png') %>" sizes="16x16">

    <meta content='True' name='HandheldFriendly'>
    <meta content='320' name='MobileOptimized'>
    <meta name="chaskiq-host" content="<%= Chaskiq::Config.get('HOST') %>"/>
    <meta name="chaskiq-ws" content="<%= Chaskiq::Config.get('WS') %>"/>

    <% if auth0_enabled? %>
      <meta name="auth0-domain" content="<%= Chaskiq::Config.get('AUTH0_DOMAIN') %>"/>
      <meta name="auth0-client-id" content="<%= Chaskiq::Config.get('AUTH0_CLIENT_ID') %>"/>
    <% elsif oauth_app = Doorkeeper::Application.first %>
      <meta name="chaskiq-client-id" content="<%= oauth_app.uid %>"/>
    <% end %>

    <!--
    <meta content='width=device-width, initial-scale=1' name='viewport'>
    <meta content='width=device-width, initial-scale=1' media='(device-height: 568px)' name='viewport'>
    -->
    <meta
      name="viewport"
      content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
    >
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css' rel='stylesheet' />

    <% #= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% #= stylesheet_pack_tag "application" %>
    <% #= javascript_pack_tag 'application' %>
    <!--<link href="https://fonts.googleapis.com/css?family=PT+Sans|Roboto+Mono&display=swap" rel="stylesheet">-->
    <!--<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500,700,800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render partial: "shared/flash" %>

    <div class="page antialiased" id="main-page">
    </div>

    <% if paddle_subscriptions? %>
      <script src="https://cdn.paddle.com/paddle/paddle.js"></script>
      <script type="text/javascript">
        Paddle.Setup({ vendor: 115475 });
      </script>
    <% end %>

    <% if current_agent.present? and
      support_data = support_app_data and
      support_data.present? %>

      <script>
        (function(d,t) {
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src="<%= Chaskiq::Config.get('HOST') %>/embed.js"
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            window.chaskiqSupport = new window.ChaskiqMessengerEncrypted({
              domain: "<%= Chaskiq::Config.get('HOST') %>",
              ws:  "<%= Chaskiq::Config.get('WS') %>",
              app_id: "<%= support_app_data[:app].key %>",
              data: <%= raw support_app_data[:enc] %>
            })
          }
        })(document,"script");
      </script>

    <% end %>

    <script>
      var dismissibleAlerts = document.querySelectorAll('.alert-dismissible');
      dismissibleAlerts.forEach(function(alert) {
          alert.querySelector('[role="button"]').addEventListener('click', function () {
            alert.classList.add('hidden');
          })
        }
      );
    </script>
  </body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @app.article_settings.site_title %></title>
    <link rel="icon" type="image/png" href="<%= @app.article_settings.logo_url %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="chaskiq-host" content="<%= ENV['HOST'] %>"/>
    <meta content='True' name='HandheldFriendly'>
    <meta content='320' name='MobileOptimized'>
    <!--<meta content='width=device-width, initial-scale=1' name='viewport'>
    <meta content='width=device-width, initial-scale=1' media='(device-height: 568px)' name='viewport'>
    -->
    <meta
      name="viewport"
      content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
    >

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://fonts.googleapis.com/css?family=PT+Sans|Roboto+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
  
  </head>

  <body>
    <div class="page" id="main-page">
    </div>


    <% if @app.article_settings && @app.article_settings.google_code %>

      <script 
        key="3"
        async 
        src="https://www.googletagmanager.com/gtag/js?id=<%= @app.article_settings.google_code %>"
      >
      </script>

      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', "<%= @app.article_settings.google_code %>" );
      </script>
    <% end %>

    <script>
      (function(d,t) {
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src="<%=@h[:http] +request.env["HTTP_HOST"]%>/embed.js"
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chaskiqMessenger = new window.ChaskiqMessengerEncrypted({
            domain: '<%=@h[:http] +request.env["HTTP_HOST"]%>',
            ws:  '<%= Rails.application.config.action_cable.url %>',
            //lang: "<%= @lang %>",
            data: {},
            app_id: "<%= @app.key %>"
          })
        }
      })(document,"script");
    </script>



  </body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaskiq CLIENT TEST</title>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= yield :head %>
  </head>

  <body>
    <%= yield :body %>
  </body>
</html>

app/views/layouts/devise.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaskiq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <% #= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="page" id="main-page">
      <%= render partial: "shared/flash" %>
      <div class="mt-6">
        <%= yield %>
      </div>
    </div>
  </body>
</html>